# Generated by Django 2.1 on 2019-07-09 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'contactus',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(default=0)),
                ('added_date', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Category')),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='ItemImageAndVideos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('path', models.CharField(blank=True, max_length=100, null=True)),
                ('item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Item')),
            ],
            options={
                'db_table': 'itemimageandvideos',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('is_read', models.IntegerField(default=0)),
                ('sender_status', models.IntegerField(default=1)),
                ('receiver_status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('table_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('sender_status', models.IntegerField(default=1)),
                ('receiver_status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('offer_status', models.IntegerField(default=0)),
                ('item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Item')),
            ],
            options={
                'db_table': 'offers',
            },
        ),
        migrations.CreateModel(
            name='OtherUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=59)),
                ('phone_no', models.CharField(default='', max_length=59)),
                ('role', models.IntegerField(default=0)),
                ('profile_pic', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(default='m', max_length=1)),
                ('otp', models.IntegerField(default=0)),
                ('otp_senttime', models.DateTimeField(null=True)),
                ('otp_verify', models.IntegerField(default=0)),
                ('address', models.CharField(default='', max_length=255)),
                ('latitude', models.CharField(max_length=255, null=True)),
                ('longitude', models.CharField(max_length=255, null=True)),
                ('username', models.CharField(default='', max_length=255)),
                ('password', models.CharField(default='', max_length=255)),
                ('save_search', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('deviceId', models.CharField(default='', max_length=191)),
                ('deviceType', models.CharField(default='', max_length=1)),
                ('onOffNotification', models.IntegerField(default=1)),
                ('timezone', models.CharField(default='', max_length=191)),
                ('created_date', models.DateField(auto_now=True, null=True)),
                ('user_auth', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'otheruser',
            },
        ),
        migrations.CreateModel(
            name='Searches',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Category')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app1.OtherUser')),
            ],
            options={
                'db_table': 'searches',
            },
        ),
        migrations.CreateModel(
            name='ShipmentDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('shippername', models.CharField(max_length=255)),
                ('package_id', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.OtherUser')),
            ],
            options={
                'db_table': 'shipmentdetails',
            },
        ),
        migrations.AddField(
            model_name='offers',
            name='offered_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app1.OtherUser'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='receiver',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_notification', to='app1.OtherUser'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_notification', to='app1.OtherUser'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_message', to='app1.OtherUser'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_message', to='app1.OtherUser'),
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app1.OtherUser'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app1.OtherUser'),
        ),
    ]
