# Generated by Django 2.1 on 2019-07-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg_time',
            field=models.DateTimeField(null=True),
        ),
    ]
