# Generated by Django 2.1 on 2019-07-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_message_msg_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notificationDate',
            field=models.DateTimeField(null='True'),
            preserve_default='True',
        ),
    ]
